app = 'mnp'
primary_region = 'sjc'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[http_service.checks]]
  grace_period = '120s'
  interval = '30s'
  timeout = '5s'
  method = 'get'
  path = '/healthz'

[mounts]
  source = 'mnp_cache'
  destination = '/cache'
